
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS useStudentsToDoLuckDraw;
CREATE TABLE useStudentsToDoLuckDraw(
    id int(10) NOT NULL AUTO_INCREMENT,
    sid VARCHAR (255) DEFAULT NULL ,
    sname VARCHAR (255) DEFAULT NULL ,
    PRIMARY KEY (id)
)ENGINE=innoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;